name: PR

'on':
  push

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional
          echo 'hello'
      - name: lint
        run: |
          echo "$PR_TITLE" | commitlint
        env:
          PR_TITLE: ${{github.event.pull_request.title}}
